### PR TITLE
Update jenkins

### PR DESCRIPTION
**Pull request by jpa198**
qcore...

### CODE REVIEW

**Review by jasonmotha — DISMISSED** [review]
it doesn't look like we mind being in the qcore direcotry for the rest of the script but it still gives me anxiety lol.

**Comment by jpa198** [comment]
> it doesn't look like we mind being in the qcore direcotry for the rest of the script but it still gives me anxiety lol.

Check line 31...

**Review by jasonmotha — DISMISSED** [review]

**Comment by jasonmotha** [comment]
That's a lot of black issues.

**Comment by jpa198** [comment]
> That's a lot of black issues.

What in tarnation? :angry:

**Review by jasonmotha — APPROVED** [review]

**Review by shot0829 — APPROVED** [review]

**Pull request merged**
