### PR TITLE
Quick bug fix for 400m vm_pert

### PR DESCRIPTION
**Pull request by joelridden**

### CODE REVIEW

**Review by jpa198 — DISMISSED** [review]

**Comment by sungeunbae** [comment]
Please add a comment why this change is needed. Thanks!

**Comment by jpa198** [comment]
Previous behaviour was to assume that the entire layer was incorporated into the model. However for layers with an odd depth (in km) and a 400m grid spacing, there would be a half grid layer rounded down per odd sized layer. The new behaviour is to only consider the size of the actual layer depth used, so every second odd sized layer will be rounded up, while the first and every second after that will be rounded down. This also allows for more complex layer models with non integer thicknesses

**Comment by sungeunbae** [comment]
Nice - but I'd prefer a shorter version of this description as a comment in the code.

**Review by sungeunbae — CHANGES_REQUESTED** [review]
Comment in the code please?

**Review by jpa198 — DISMISSED** [review]

**Review by jpa198 — APPROVED** [review]

**Review by sungeunbae — APPROVED** [review]

**Pull request merged**
