### PR TITLE
Add escape for single realisation events to not need the _REL suffix

### PR DESCRIPTION
**Pull request by jpa198**

### CODE REVIEW

**Review by shot0829 — DISMISSED** [review]

**Comment by shot0829** [comment]
I remember we have this logic somewhere else as well? can we not re-use it?

**Comment by jpa198** [comment]
> I remember we have this logic somewhere else as well? can we not re-use it?

I don't think we do? Off the top of my head/quick look says we use "if n_rels==1: no REL, else REL". We could add a parameter to get_realisation_name that would take in the number of realisations for that event and just return the event name if it's 1, but I'm not sure if that's a good idea as it may provide false security

**Review by jasonmotha — COMMENTED** [review]
Won't this rename the first realisation always?

```
       get_realisation_name(pid, i + 1) if faults[pid] > 1 else pid
```

**Comment by jpa198** [comment]
> Won't this rename the first realisation always?
> 
> ```
>        get_realisation_name(pid, i + 1) if faults[pid] > 1 else pid
> ```

Yeah... Good spotting

**Review by jasonmotha — APPROVED** [review]

**Review by shot0829 — APPROVED** [review]

**Pull request merged**
