### PR TITLE
Unrotated horizontal acceleration components

### PR DESCRIPTION
**Pull request by claudio525**
Added support for writing unrotated horizontal acceleration components

### CODE REVIEW

**Review by jasonmotha — APPROVED** [review]
So, two new additional components H1 and H2?

**Comment by claudio525** [comment]
> So, two new additional components H1 and H2?
@jasonmotha Yeah, they are the unrotated horizontal components, thats what @lee-robin wanted

**Review by jpa198 — APPROVED** [review]

**Comment by jpa198** [comment]
> > So, two new additional components H1 and H2?
> 
> @jasonmotha Yeah, they are the unrotated horizontal components, thats what @lee-robin wanted

Yeah, we'll need to add H1 and H2 to the components enum. Looks like it won't be an issue till we do the IM_calc funcitonality, if even then

**Comment by jasonmotha** [comment]
> > > So, two new additional components H1 and H2?
> > 
> > 
> > @jasonmotha Yeah, they are the unrotated horizontal components, thats what @lee-robin wanted
> 
> Yeah, we'll need to add H1 and H2 to the components enum. Looks like it won't be an issue till we do the IM_calc funcitonality, if even then

Yeah. I believe we need IM_calc functionality as part of the GMDB / NZSHM project but that's an until-it's-asked-for problem.

**Comment by jasonmotha** [comment]
My only question is does it matter which direction H1 / H2 are?

**Comment by claudio525** [comment]
> My only question is does it matter which direction H1 / H2 are?
> 
> Or is H1 closer to 000 or something like that? Or just whack in general?

@jasonmotha Not sure, I feel like thats a @lee-robin  question. 
For V1A files I just the wrapper to load the file and then use acc_1 as acc_h1 and and acc_2 as acc_h2, which then become acc_000 and acc_090 respectively.
Miniseed the same, just use the component that has a 1 in t as a h2 and the one that has a 2 as h2.

**Comment by lee-robin** [comment]
> 
> 
> > My only question is does it matter which direction H1 / H2 are?
> > Or is H1 closer to 000 or something like that? Or just whack in general?
> 
> @jasonmotha Not sure, I feel like thats a @lee-robin question.
> For V1A files I just the wrapper to load the file and then use acc_1 as acc_h1 and and acc_2 as acc_h2, which then become acc_000 and acc_090 respectively.
> Miniseed the same, just use the component that has a 1 in t as a h2 and the one that has a 2 as h2.

H1 and H2 basically just refer to the data channel, which just depends on how the instrument was installed. Generally H1 direction is given and then H2 is 90 degrees clockwise I think.

**Comment by lee-robin** [comment]
> 
> 
> > > > So, two new additional components H1 and H2?
> > > 
> > > 
> > > @jasonmotha Yeah, they are the unrotated horizontal components, thats what @lee-robin wanted
> > 
> > 
> > Yeah, we'll need to add H1 and H2 to the components enum. Looks like it won't be an issue till we do the IM_calc funcitonality, if even then
> 
> Yeah. I believe we need IM_calc functionality as part of the GMDB / NZSHM project but that's an until-it's-asked-for problem.

Ideally we do this once this change is confirmed, but based on timing it seems like we'll talk about it on Monday.

**Review by lee-robin — APPROVED** [review]

**Pull request merged**
